spring:
  application:
    name: customer
  data:
    mongodb:
      username: mongodb
      password: safwene17
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true