spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: safwene17
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:org.ecommerce.notification.kafka.order.OrderConfirmation, paymentConfirmation:org.ecommerce.notification.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: safwene
    password: safwene17
    protocol:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connection-timeout: 5000
        timeout: 3000
        write-timeout: 5000

server:
    port: 8040