spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: safwene17
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    baseline-description: init
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8050
